version: "3"

services:
  postgres:
    image: "postgres:11.5"
    container_name: "db_postgres"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=finance_api"
    expose:
      - "5432"
    ports:
      - "5432:5432"